import Navbar from '@/components/Navbar';
import './globals.css';
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ThenCrypto',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang='en' className='snap-y snap-mandatory h-screen overflow-y-scroll overflow-x-hidden'>
        <body className={`${inter.className} bg-[#347fc4]`}>
          <Navbar />
          {children}
        </body>
      </html>
    </>
  )
}


